name: remove /home/
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: remove /home/
        run: |
          if [[ -z 'grep -rlZ "/home/" . --exclude-dir=.git --exclude-dir=.github' ]]; then
            grep -rlZ "/home/" . --exclude-dir=.git --exclude-dir=.github | xargs -0 sed -i "s/\/home//g"
          fi
      - name: commit changes
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull origin main
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "remove /home/"
            git push origin main
          fi
